[package]
name = "avifweaver"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
pic-scale = { version = "0.3.0", default-features = false }
yuvutils-rs = "0.5.9"
bytemuck = "1.19.0"

[lib]
crate-type = ["cdylib", "staticlib"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3  # Optimize for size.
lto = true  # Enable link time optimization
codegen-units = 1  # Reduce parallel code generation units
panic = "abort"

[build-dependencies]
cbindgen = "0.27.0"