[package]
name = "avifweaver"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
pic-scale = { version = "0.5.4", default-features = false, features = ["nightly_f16"] }
yuvutils-rs = { path = "../../../RustroverProjects/yuvutils-rs", features = ["nightly_f16"], default-features = false }
bytemuck = { version = "1.22", features = ["nightly_float"] }
moxcms = {path = "../../../RustroverProjects/moxcms"}
gainforge = {path = "../../../RustroverProjects/gainforge"}

[features]
rdm = ["yuvutils-rs/rdm", "pic-scale/rdm"]

[lib]
crate-type = ["cdylib", "staticlib"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = 3  # Optimize for size.
lto = true  # Enable link time optimization
codegen-units = 1  # Reduce parallel code generation units

[build-dependencies]
cbindgen = "0.28.0"